Flowpack:
  ElasticSearch:
    ContentRepositoryQueueIndexer:
      enableLiveAsyncIndexing: true

  JobQueue:
    Common:
      presets:
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer':
          className: 'Flowpack\JobQueue\Beanstalkd\Queue\BeanstalkdQueue'
          executeIsolated: true
          options:
            host: '127.0.0.1'
            port: 11300

      queues:
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer':
          preset: 'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer'

        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer.Live':
          preset: 'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer'
