Flowpack:

  ElasticSearch:

    ContentRepositoryQueueIndexer:

      enableLiveAsyncIndexing: true

  JobQueue:

    Common:
      queues:
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer':
          className: 'Flowpack\JobQueue\Beanstalkd\Queue\BeanstalkdQueue'
          executeIsolated: true
          options:
            client:
              host: '127.0.0.1'
              port: 11300

        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer.Live':
          className: 'Flowpack\JobQueue\Beanstalkd\Queue\BeanstalkdQueue'
          executeIsolated: true
          options:
            client:
              host: '127.0.0.1'
              port: 11300
