TYPO3:
  Jobqueue:
    Common:
      queues:
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer':
          className: 'TYPO3\Jobqueue\Beanstalkd\Queue\BeanstalkdQueue'
          options:
            host: '127.0.0.1'
            port: 11300
