Flowpack:
  ElasticSearch:
    ContentRepositoryQueueIndexer:
      enableLiveAsyncIndexing: true
      # Change size of single batch jobs via this setting
      batchSize: 500

      # Number of failed jobs accepted to switch the alias to the new index
      # -1 means, accept any number of failures
      acceptedFailedJobs: 0

      # Run a nodeindex:cleanup after the node switching job switched the index
      cleanupIndicesAfterSuccessfulSwitch: true
  JobQueue:
    Common:
      queues:
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer':
          preset: 'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer'

        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer.Live':
          preset: 'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer'

      presets:
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer':
          className: 'Flowpack\JobQueue\Common\Queue\FakeQueue'
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer.Live':
          className: 'Flowpack\JobQueue\Common\Queue\FakeQueue'
