Flowpack:
  ElasticSearch:
    ContentRepositoryQueueIndexer:
      enableLiveAsyncIndexing: true
      batchSize: 500

  JobQueue:
    Common:
      queues:
        'Flowpack-ES-NeosCR-QueueIndexer':
          className: 'Flowpack\JobQueue\Beanstalkd\Queue\BeanstalkdQueue'
          executeIsolated: true
          options:
            host: '127.0.0.1'
            port: 11300

        'Flowpack-ES-NeosCR-QueueIndexer-Live':
          className: 'Flowpack\JobQueue\Beanstalkd\Queue\BeanstalkdQueue'
          executeIsolated: true
          options:
            host: '127.0.0.1'
            port: 11300
