Flowpack:
  ElasticSearch:
    ContentRepositoryQueueIndexer:
      enableLiveAsyncIndexing: true
      # Change size of single batch jobs via this setting (fallback default is 500)
      # batchSize: 50
  JobQueue:
    Common:
      presets:
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer':
          className: 'Flowpack\JobQueue\Beanstalkd\Queue\BeanstalkdQueue'
          executeIsolated: true
          options:
            client:
              host: '127.0.0.1'
              port: 11300

      queues:
        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer':
          preset: 'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer'

        'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer.Live':
          preset: 'Flowpack.ElasticSearch.ContentRepositoryQueueIndexer'
